# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8a8f663458cfe80d32f5c7cd132df44a3ed156525e4bb3b998c97dd651bd01af5fb06594c6cece01f4b371aaa16c966063e23acc32d281aae2f0f6a0afe3424

test:
  secret_key_base: 7c2eb26428b299d083fd46ee7571df026e726e198e3c2b192109d4470e6d492cb0bf93cf2403ad1fa6ace67302d4bfcb9894227111ddb0374fcc8dd648718fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
